### ISSUE TITLE
stats functionality doesnt work for VlnPlot2

### ISSUE THREAD

**Issue by Eomesodermin** [huayc09/SeuratExtend#10]
I'm not sure how to debug this because not getting any error. The below function call works fine in that a plot is generated. But stats are not computed or put on the plot. 

I have tried many iterations but can't seem to work out why stats are not being applied. 

Any advice. 

VlnPlot2(srt_tcells, features = "P2rx7", group.by = "genotype", stats.method = "wilcox.test", hide.ns = F)

<img width="729" alt="Screenshot 2024-08-28 at 11 21 50 am" src="https://github.com/user-attachments/assets/3edddbac-b8e0-419e-973b-d79b9cf06a17">

**Comment by huayc09** [comment]
Hi, you should use 'stat.method' instead of 'stat**s**.method' :)

**Comment by Eomesodermin** [comment]
omg, how silly of me. 

but now I actually have an error 

Error: unable to find an inherited method for function ‘select’ for signature ‘x = "grouped_df"’

**Comment by huayc09** [comment]
Thank you for reporting this issue. It appears to be similar to the problem described in #5. 

Previously, my suspicion was that this might be related to the `select` function. Multiple packages have a `select` function, and it's possible that when `VlnPlot2` was trying to use `dplyr::select` internally, it was being masked by another package's `select` function.

I've recently updated the `VlnPlot2` function to explicitly specify that it's using the `select` function from the dplyr package. Could you please try upgrading SeuratExtend to the latest version and see if the error still persists?
