### ISSUE TITLE
reverse order of the cluster values in the ClusterDistrBar

### ISSUE THREAD

**Issue by pcantalupo** [huayc09/SeuratExtend#11]
In the vignette, B cell is plotted at the bottom of the stacked bars. How do I reverse the order so that B cell is at the top, then CD4 memory below it, etc...  I tried to reverse the factor levels but it did not work.
![image](https://github.com/user-attachments/assets/0c9a8ef9-f075-4b26-8669-38f67e68965e)

**Comment by huayc09** [comment]
Thank you for your question. I've just added a new parameter `reverse_order` to the `ClusterDistrBar` function to make it easier to adjust the stacking order. By default, it's set to `TRUE`, so you can simply set it to `FALSE` to reverse the order. Here's an example:

```R
ClusterDistrBar(origin = pbmc$orig.ident, cluster = pbmc$cluster, flip = FALSE, reverse_order = FALSE)
```

This should place B cells at the top of the stacked bars, followed by CD4 memory cells, and so on.

You can try this out by updating to the latest version of SeuratExtend. Let me know if it works for you!

**Comment by pcantalupo** [comment]
That worked Thank you.   

However, I don't see the option in the documentation for ClusterDistrBar.

**Comment by huayc09** [comment]
Thank you for reminding. Apologize for my oversight. I've just added the documentation in the new update. It should be visible now. :)
