### ISSUE TITLE
Matrix版本匹配问题

### ISSUE THREAD

**Issue by PanSX-Dr** [huayc09/SeuratExtend#16]
您好，我今天发现seuratextend神奇的包，然后安装想尝试一下，当我运行的时候提示我seuratextend依赖的是Matrix1.70版本，但是之前我的Matrix已经更新到了1.71版本，请问这会有影响么？

**Comment by huayc09** [comment]
咦，我没有遇到过这个问题。如果没有报错的话应该是没影响的。

SeuratExtend本身对Matrix的版本没有限制，可能是其他的依赖的包。理论上Seurat能用的话SeuratExtend就能用。
