### ISSUE TITLE
DEGs GSEAplot function

### ISSUE THREAD

**Issue by SudoSchrodinger** [huayc09/SeuratExtend#19]
@huayc09  Thank you for the package, it's amazing.
I have a question: is the GSEAplot analysis performed with the DEGs from the Seurat object?
I appreciate the help.

**Comment by huayc09** [comment]
The GSEAplot function actually uses all expressed genes in the dataset, not just the differentially expressed genes (DEGs). This is consistent with the original GSEA methodology from the Broad Institute, where all genes are ranked based on their differential expression between two conditions, and then the distribution of a gene set is examined across this complete ranking.

Here's how it works in our implementation:
1. All genes are ranked by their log fold change between the two specified cell types/conditions
2. A running enrichment score is calculated by walking down this ranked list
3. This comprehensive approach allows us to detect subtle but coordinated changes in gene sets that might be missed when using only DEGs

For those interested in learning more about interpreting GSEA plots, I recommend checking out the GSEA User Guide: https://www.gsea-msigdb.org/gsea/doc/GSEAUserGuideTEXT.htm#_Enrichment_Score_(ES)

**Comment by SudoSchrodinger** [comment]
Thanks for your help. I understood. 
Great package!
