### ISSUE TITLE
DotPlot2 throws error when feature(s) not present in data

### ISSUE THREAD

**Issue by JackieMium** [huayc09/SeuratExtend#22]
With `Seurat::DotPlot()`, if some of the provided features are not present in the data, it throws a warning message and moves on to plot by skipping these features. However, `SeuratExtend::DotPlot2()` warns too but refuses to plot. Minimal example below.

The data is the [Seurat guided tutorial `pbmc3k`](https://satijalab.org/seurat/articles/pbmc3k_tutorial).
```
grouped_features <- list(
   NaiCD4 = c('IL7R', 'CCR7'),
   Mono1 =  c('CD14', 'LYZ'),
   MemCD4 = c('S100A4', 'CD4'),
   B = c('MS4A1'),
   CD8T = c('CD8A', 'CD8'),  # <--- CD8 does not exist in the data 
   Mono2 = c('FCGR3A', 'MS4A7'),
   NK = c('GNLY', 'NKG7'),
   DC = c('FCER1A', 'CST3'),
   Plt = c('PPBP')
)
```
While `Seurat::DotPlot(pbmc, features = as.vector(unlist(grouped_features))) & RotatedAxis()` warns:

```
Warning message:
“The following requested variables were not found: CD8”
```

but we still get

![image](https://github.com/user-attachments/assets/dd8b1407-56de-45fa-9112-3235bc6fab8c)

However, `SeuratExtend::DotPlot2(pbmc, features = grouped_features)` will refuse to plot:

```
Warning message:
“The following requested variables were not found: CD8”
Warning message:
“The following requested variables were not found: CD8”

Error in `$<-.data.frame`(`*tmp*`, "FeatureGroup", value = c("NaiCD4", : replacement has 144 rows, data has 135
Traceback:
```

A fix could be checking the feature lists and omitting the ones that are not in the data:

```
grouped_features <- lapply(
    grouped_features, 
    \(f) {
        if(length(intersect(f, rownames(pbmc))) == 0)
            f = NULL
        else
            f = intersect(f, rownames(pbmc))
        return(f)
} )
grouped_features[sapply(grouped_features, is.null)] <- NULL
```

With this `SeuratExtend::DotPlot2(pbmc, features = grouped_features)` will work. 
Another thing is, we should probably check for duplicated featues and also keep only one before plotting, or throws an error and indicate which ones are duplicated. `Seurat` will just throws an error and complains about duplicated features without telling you which ones are duplicated.

**Comment by huayc09** [comment]
Thanks for raising this issue - great suggestions! I've implemented the fix in v1.1.1 by adding feature validation and duplicate handling. 

Here's a quick example using the PBMC3K dataset:

```r
grouped_features <- list(
   NaiCD4 = c('IL7R', 'CCR7'),
   Mono1 =  c('CD14', 'LYZ'),
   CD8T = c('CD8A', 'CD8'),  # CD8 doesn't exist
   B = c('MS4A1', 'CD14')    # CD14 is duplicate
)

DotPlot2(pbmc, features = grouped_features)
# Will warn about:
# - Missing 'CD8'
# - Duplicate 'CD14' (keeping first occurrence in Mono1)
# Then proceed with the plot
```

Thanks for helping improve SeuratExtend!
