### ISSUE TITLE
An error occurred when running Palantir.Pseudotime in windows

### ISSUE THREAD

**Issue by SEvisual** [huayc09/SeuratExtend#24]
Hi, 

I run the following code and get an error message:

```
library(Seurat)
library(SeuratExtend)
mye_small <- readRDS(url("https://zenodo.org/records/10944066/files/pbmc10k_mye_small_velocyto.rds", "rb"))
mye_small <- Palantir.RunDM(mye_small)
mye_small <- SeuratExtend::Palantir.Pseudotime(mye_small, start_cell = "sample1_GAGAGGTAGCAGTACG-1")

```

_Sampling and flocking waypoints...
Time for determining waypoints: 0.00042071342468261717 minutes
Determining pseudotime...
Shortest path distances using 30-nearest neighbor graph...
py_run_string_impl(code, local, convert): 
  **UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)**_

After checking, I found that n_jobs in palantir.core.run_palantir defaults to -1 to cause this error, and setting n_jobs to 1 will work properly. Can add a parameter or set it to 1?

`specific_code <- "pr_res=palantir.core.run_palantir(ms_data, start_cell, num_waypoints=500, n_jobs=1)"`

**Comment by huayc09** [comment]
Thank you for reporting this issue! This is the first time this UnicodeEncodeError has been reported, and I appreciate you sharing both the problem and your solution.

I've added the `n_jobs` parameter to the `Palantir.Pseudotime` function with a default value of 1 as you suggested. Could you try this updated version and let me know if it resolves the encoding issue for you?

If you encounter any other issues, please don't hesitate to report them.

**Comment by huayc09** [comment]
Thanks for the additional report. I've also added the `n_jobs` parameter to the `Palantir.Magic` function with the same default value of 1. This should help prevent similar encoding issues when running MAGIC imputation. Please try it out and let me know if you encounter any other problems.
